/**
 * app/api/download/route.ts
 *
 * GET /api/download?token=<JWT>
 *
 * Called when user clicks the download link in their email.
 *
 * Flow:
 *   1. Verify JWT (signature + expiry)
 *   2. Check token is not already used (one-time-use)
 *   3. Fetch pack from Supabase
 *   4. Build ZIP in memory
 *   5. Mark token used
 *   6. Stream ZIP as attachment
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import JSZip from 'jszip'
import { verifyDownloadToken } from '@/lib/services/token.service'
import type { GeneratedImage } from '@/lib/types'

export const maxDuration = 30

export async function GET(request: NextRequest) {
  try {
    const token = request.nextUrl.searchParams.get('token')
    if (!token) return htmlError('Missing download token.', 400)

    // 1. Verify JWT
    let payload: Awaited<ReturnType<typeof verifyDownloadToken>>
    try {
      payload = await verifyDownloadToken(token)
    } catch {
      return htmlError('This download link is invalid or has expired.', 401)
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
    )

    // 2. One-time-use check
    const { data: tokenRecord, error: tokenError } = await supabase
      .from('download_requests')
      .select('id, token_used')
      .eq('jwt_token', payload.jti)
      .single()

    if (tokenError || !tokenRecord) {
      console.error('[download] Token lookup failed:', {
        jti: payload.jti,
        errorCode: tokenError?.code,
        errorMsg: tokenError?.message,
        errorHint: tokenError?.hint,
        hasRecord: !!tokenRecord,
      })
      return htmlError('Download link not found. This can happen if the pack failed to save — please generate a new pack.', 404)
    }
    if (tokenRecord.token_used) {
      return htmlError('This link has already been used. Generate a new pack to get a fresh link.', 410)
    }

    // 3. Fetch pack
    const { data: pack, error: packError } = await supabase
      .from('packs')
      .select('images_data, platform, audience')
      .eq('id', payload.packId)
      .single()

    if (packError || !pack) {
      console.error('[download] Pack fetch failed:', { packId: payload.packId, error: packError?.message })
      return htmlError('Pack not found or has expired. Please generate a new one.', 404)
    }

    const images: GeneratedImage[] = pack.images_data

    // 4. Build ZIP
    const zip = new JSZip()
    const imagesFolder = zip.folder('images')!

    // Images — variation-A-lifestyle.png etc.
    const VARIATION_LETTERS = ['A', 'B', 'C', 'D']
    for (const image of images) {
      if (image.status !== 'done' || !image.imageBase64) continue
      const base64 = image.imageBase64.replace(/^data:image\/\w+;base64,/, '')
      const ext = image.imageBase64.startsWith('data:image/jpeg') ? 'jpg' : 'png'
      const letter = VARIATION_LETTERS[image.variation - 1] ?? String(image.variation)
      imagesFolder.file(`variation-${letter}-${image.angle}.${ext}`, base64, { base64: true })
    }

    // Ad copy
    const adLines: string[] = [
      'PIXPACK — AD COPY',
      '='.repeat(50),
      `Platform: ${(pack.platform ?? '').replace(/_/g, ' ').toUpperCase()}`,
      '',
    ]
    for (const image of images) {
      if (image.status !== 'done') continue
      const letter = VARIATION_LETTERS[image.variation - 1] ?? String(image.variation)
      adLines.push('─'.repeat(40))
      adLines.push(`VARIATION ${letter} — ${image.angle.toUpperCase()}`)
      adLines.push('─'.repeat(40))
      adLines.push(`\nAWARENESS:\n${image.adCopy.awareness}\n`)
      adLines.push(`CONSIDERATION:\n${image.adCopy.consideration}\n`)
      adLines.push(`CONVERSION:\n${image.adCopy.conversion}\n`)
    }
    zip.file('ad_copy.txt', adLines.join('\n'))

    // README
    const successCount = images.filter(i => i.status === 'done').length
    const platformLabel = (pack.platform ?? 'unknown').replace(/_/g, ' ').toUpperCase()
    zip.file('README.txt', [
      'PIXPACK — A/B TEST VARIATIONS', '='.repeat(40), '',
      `Platform:   ${platformLabel}`,
      `Variations: ${successCount} generated`,
      `Generated:  ${new Date().toLocaleString()}`,
      '',
      'FILES',
      '─'.repeat(40),
      'images/',
      '  variation-A-lifestyle.ext   Candid lifestyle scene',
      '  variation-B-hero.ext        Studio hero shot',
      '  variation-C-context.ext     Aspirational context',
      '  variation-D-closeup.ext     Material detail macro',
      'ad_copy.txt                   Awareness / Consideration / Conversion per variation',
      '',
      'HOW TO USE',
      '─'.repeat(40),
      'Upload all 4 to your ads manager, split budget equally,',
      'run for 7–14 days, keep the winner.',
      '',
      `Generated by PixPack — ${process.env.NEXT_PUBLIC_SITE_URL}`,
    ].join('\n'))

    // 5. Mark token used
    await supabase
      .from('download_requests')
      .update({ token_used: true, downloaded_at: new Date().toISOString() })
      .eq('id', tokenRecord.id)

    // 6. Stream ZIP
    const zipBuffer = await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' })
    const filename = `pixpack_${new Date().toISOString().slice(0, 10)}.zip`

    const blob = new Blob([zipBuffer] as unknown as BlobPart[], { type: 'application/zip' })

    return new NextResponse(blob as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': blob.size.toString(),
        'Cache-Control': 'no-store',
      },
    })

  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Internal server error'
    console.error('[download] Fatal:', message)
    return htmlError('Something went wrong. Please try again.', 500)
  }
}

function htmlError(message: string, status: number): NextResponse {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? '/'
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>PixPack — Download Error</title>
  <style>
    body{font-family:system-ui,sans-serif;background:#0c0c0b;color:#f0ece3;
         display:flex;align-items:center;justify-content:center;
         min-height:100vh;margin:0;padding:24px;box-sizing:border-box}
    .card{max-width:400px;text-align:center}
    .logo{font-size:24px;font-weight:700;margin-bottom:24px}
    .logo span{color:#ff4d1c}
    p{color:#6b6760;line-height:1.6;margin-bottom:24px}
    a{color:#ff4d1c;text-decoration:none}
  </style>
</head>
<body>
  <div class="card">
    <div class="logo">Pix<span>Pack</span></div>
    <p>${message}</p>
    <a href="${siteUrl}">← Back to PixPack</a>
  </div>
</body>
</html>`
  return new NextResponse(html, { status, headers: { 'Content-Type': 'text/html' } })
}