/**
 * app/api/download/route.ts
 *
 * GET /api/download?token=<JWT>
 *
 * Called when user clicks the download link in their email.
 *
 * Flow:
 *   1. Verify JWT (signature + expiry)
 *   2. Check token is not already used (one-time-use)
 *   3. Fetch pack from Supabase
 *   4. Build ZIP in memory
 *   5. Mark token used
 *   6. Stream ZIP as attachment
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import JSZip from 'jszip'
import { verifyDownloadToken } from '@/lib/services/token.service'
import type { GeneratedImage, ProductDescription, PostingSlot } from '@/lib/types'

export const maxDuration = 30

export async function GET(request: NextRequest) {
  try {
    const token = request.nextUrl.searchParams.get('token')
    if (!token) return htmlError('Missing download token.', 400)

    // 1. Verify JWT
    let payload: Awaited<ReturnType<typeof verifyDownloadToken>>
    try {
      payload = await verifyDownloadToken(token)
    } catch {
      return htmlError('This download link is invalid or has expired.', 401)
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
    )

    // 2. One-time-use check
    const { data: tokenRecord, error: tokenError } = await supabase
      .from('download_requests')
      .select('id, token_used')
      .eq('jwt_token', payload.jti)
      .single()

    if (tokenError || !tokenRecord) {
      console.error('[download] Token lookup failed:', {
        jti: payload.jti,
        errorCode: tokenError?.code,
        errorMsg: tokenError?.message,
        errorHint: tokenError?.hint,
        hasRecord: !!tokenRecord,
      })
      return htmlError('Download link not found. This can happen if the pack failed to save — please generate a new pack.', 404)
    }
    if (tokenRecord.token_used) {
      return htmlError('This link has already been used. Generate a new pack to get a fresh link.', 410)
    }

    // 3. Fetch pack
    const { data: pack, error: packError } = await supabase
      .from('packs')
      .select('images_data, product_description, posting_schedule, audience, total_score')
      .eq('id', payload.packId)
      .single()

    if (packError || !pack) {
      return htmlError('Pack not found or has expired. Please generate a new one.', 404)
    }

    const images = pack.images_data as GeneratedImage[]
    const desc = pack.product_description as ProductDescription
    const schedule = pack.posting_schedule as PostingSlot[]

    // 4. Build ZIP
    const zip = new JSZip()
    const imagesFolder = zip.folder('images')!

    // Images
    for (const image of images) {
      if (image.status !== 'done' || !image.imageBase64) continue
      const base64 = image.imageBase64.replace(/^data:image\/\w+;base64,/, '')
      const ext = image.imageBase64.startsWith('data:image/jpeg') ? 'jpg' : 'png'
      imagesFolder.file(`${image.platform}.${ext}`, base64, { base64: true })
    }

    // Ad copy
    const adLines: string[] = ['PIXPACK — AD COPY VARIANTS', '='.repeat(50), '']
    for (const image of images) {
      if (image.status !== 'done') continue
      adLines.push(`PLATFORM: ${image.platform.replace(/_/g, ' ').toUpperCase()}`)
      adLines.push('-'.repeat(30))
      adLines.push(`AWARENESS:\n${image.adCopy.awareness}\n`)
      adLines.push(`CONSIDERATION:\n${image.adCopy.consideration}\n`)
      adLines.push(`CONVERSION:\n${image.adCopy.conversion}\n\n`)
    }
    zip.file('ad_copy.txt', adLines.join('\n'))

    // Shopify listing
    zip.file('shopify_listing.txt', [
      'PIXPACK — SHOPIFY PRODUCT LISTING', '='.repeat(50), '',
      `TITLE:\n${desc.title}`, '',
      `TAGLINE:\n${desc.subtitle}`, '',
      'DESCRIPTION BULLETS:',
      ...desc.bulletFeatures.map(f => `• ${f}`), '',
      `SEO META TITLE:\n${desc.seoMetaTitle}`, '',
      `SEO META DESCRIPTION:\n${desc.seoMetaDescription}`,
    ].join('\n'))

    // Posting schedule
    const schedLines: string[] = ['PIXPACK — POSTING SCHEDULE', '='.repeat(50), '']
    for (const slot of schedule) {
      schedLines.push(`${slot.platform.replace(/_/g, ' ').toUpperCase()}`)
      schedLines.push(`  Best day:  ${slot.bestDay}`)
      schedLines.push(`  Best time: ${slot.bestTime} (${slot.timezone})`)
      schedLines.push(`  Why:       ${slot.reason}\n`)
    }
    zip.file('posting_schedule.txt', schedLines.join('\n'))

    // README
    zip.file('README.txt', [
      'Your PixPack Content Pack', '='.repeat(50), '',
      'FILES:',
      '  images/              Platform-native images',
      '  ad_copy.txt          3 ad variants per platform',
      '  shopify_listing.txt  Ready-to-paste product listing',
      '  posting_schedule.txt Best posting times per platform',
      '',
      `Generated by PixPack — ${process.env.NEXT_PUBLIC_SITE_URL}`,
    ].join('\n'))

    // 5. Mark token used
    await supabase
      .from('download_requests')
      .update({ token_used: true, downloaded_at: new Date().toISOString() })
      .eq('id', tokenRecord.id)

    // 6. Stream ZIP
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
    const filename = `pixpack_${new Date().toISOString().slice(0, 10)}.zip`

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': zipBuffer.byteLength.toString(),
        'Cache-Control': 'no-store',
      },
    })

  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Internal server error'
    console.error('[download] Fatal:', message)
    return htmlError('Something went wrong. Please try again.', 500)
  }
}

function htmlError(message: string, status: number): NextResponse {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? '/'
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>PixPack — Download Error</title>
  <style>
    body{font-family:system-ui,sans-serif;background:#0c0c0b;color:#f0ece3;
         display:flex;align-items:center;justify-content:center;
         min-height:100vh;margin:0;padding:24px;box-sizing:border-box}
    .card{max-width:400px;text-align:center}
    .logo{font-size:24px;font-weight:700;margin-bottom:24px}
    .logo span{color:#ff4d1c}
    p{color:#6b6760;line-height:1.6;margin-bottom:24px}
    a{color:#ff4d1c;text-decoration:none}
  </style>
</head>
<body>
  <div class="card">
    <div class="logo">Pix<span>Pack</span></div>
    <p>${message}</p>
    <a href="${siteUrl}">← Back to PixPack</a>
  </div>
</body>
</html>`
  return new NextResponse(html, { status, headers: { 'Content-Type': 'text/html' } })
}