/**
 * app/api/generate/route.ts
 *
 * POST /api/generate
 *
 * Replaces both the old SSE route AND the Upstash queue enqueue route.
 *
 * Flow:
 *   1. Validate input
 *   2. Trigger the Trigger.dev task (non-blocking, returns instantly)
 *   3. Return { runId, publicAccessToken } to client
 *
 * The client uses runId + publicAccessToken to subscribe via useRealtimeRun.
 * The task runs on Trigger.dev's infrastructure — no Vercel timeout risk.
 *
 * The publicAccessToken is auto-generated by Trigger.dev when triggering.
 * It is a scoped JWT — only grants read access to this specific run.
 * Safe to send to the frontend.
 */

import { NextRequest, NextResponse } from 'next/server'
import { tasks } from '@trigger.dev/sdk/v3'
import type { generatePackTask } from '@/trigger/generate-pack'
import type { GenerateInput } from '@/lib/services/generate.service'

export const maxDuration = 15  // Just needs to trigger the task — very fast

export async function POST(request: NextRequest) {
    try {
        const body = await request.json()
        const { productProfile, userConfig, marketingLanguage = 'auto' } = body

        // Validate
        if (!productProfile?.extractedImageUrl) {
            return NextResponse.json(
                { error: 'productProfile.extractedImageUrl is required' },
                { status: 400 },
            )
        }
        if (!userConfig?.platform) {
            return NextResponse.json(
                { error: 'userConfig.platform is required' },
                { status: 400 },
            )
        }

        const input: GenerateInput = { productProfile, userConfig, marketingLanguage }

        // Trigger the task — returns immediately with a handle
        // handle.publicAccessToken is auto-generated — safe to send to frontend
        const handle = await tasks.trigger<typeof generatePackTask>(
            'generate-pack',
            { input },
        )

        console.log(`[generate] Triggered run ${handle.id} for platform ${userConfig.platform}`)

        return NextResponse.json({
            runId: handle.id,
            publicAccessToken: handle.publicAccessToken,
        })

    } catch (err: unknown) {
        const message = err instanceof Error ? err.message : 'Failed to start generation'
        console.error('[generate] Error:', message)
        return NextResponse.json({ error: message }, { status: 500 })
    }
}